### SignUp User
POST http://localhost:4000/user
Content-Type: application/json

{
  "firstName": "Mohan",
  "lastName": "Barman",
  "email": "u0@gmail.com",
  "password": "jskasdasdlda"
}

### SignIp User
POST http://localhost:4000/user/signIn
Content-Type: application/json
Cookie: connect.sid=s%3AhxlH7Kx_Tewj28SBmLyFB6T-cMnYwFxz.jk3R7OHNRcgrqxhpSALxuiz7OVC6eyK4b1ToTEM5l%2FQ; Path=/; Expires=Sun, 05 Sep 2021 18:33:18 GMT; HttpOnly

{
  "password": "jskasdasdlda",
  "email": "u0@gmail.com"
}

### getting the current logged in user
GET http://localhost:4000/user/me
Cookie: connect.sid=s%3AhxlH7Kx_Tewj28SBmLyFB6T-cMnYwFxz.jk3R7OHNRcgrqxhC6eyK4b1ToTEM5l%2FQ; Path=/; Expires=Sun, 05 Sep 2021 18:33:18 GMT; HttpOnly